import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
  title: "Genesis",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/logo_dpo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <meta charSet="UTF-8" />
        <link rel="icon" href="/assets/images/logo_dpo.png" type="image/png" />
      </head>
      <body className="antialiased">
        {children}

        {/* Toasts aparecerão no canto inferior direito */}
        <ToastContainer
          position="bottom-right"
          autoClose={3000}
          hideProgressBar={false}
          pauseOnHover
          draggable
          theme="colored"
        />
      </body>
    </html>
  );
}
